### ISSUE TITLE
Damage enabled = false still drowns you

### ISSUE THREAD

**Issue by tenplus1** [BlockMen/hud_hunger#16]
When enable_damage = false you can still drown while using hud so a little code change to init.lua's update_hud(player) function:

```
    --air
    local air = tonumber(hud.air[name])
    if player:get_breath() ~= air then

        -- if damage not enabled then you cannot drown
        if minetest.setting_getbool("enable_damage") == "false" then
            air = 11
        else
            air = player:get_breath()
        end

        hud.air[name] = air
        if air > 10 then air = 0 end
        player:hud_change(air_hud[name], "number", air*2)
    end
```

**Comment by BlockMen** [comment]
The title is kinda confusing, so correct me if I got you wrong.

This mod only displays the players breath, so if you can really take damage (and not just disappearing bubbles) it an engine bug, since the breath is never changed/set except here: https://github.com/BlockMen/hud/blob/master/init.lua#L275

**Comment by BlockMen** [comment]
Please open new issue if present in Version 2.0 or later

**Comment by mdoege** [comment]
Already reported: https://github.com/minetest/minetest/issues/2501
