### ISSUE TITLE
Split mod

### ISSUE THREAD

**Issue by iqualfragile** [BlockMen/hud_hunger#6]
This mod should be split or at least be made into a modpack.
especially moving the adding hunger and displaying hunger functions into two different mods is important.

**Comment by MirceaKitsune** [comment]
I fully agree with splitting "hunger" and "HUD" into two different mods, since they are both different things. The HUD additions can work by themselves, while the hunger mod could have it as a non-obligatory dependency... since hunger can theoretically work without the HUD but might be unusable without a way to see the hunger level.

**Comment by BlockMen** [comment]
1071c7f13e491b2f3bc09bbbcb1bd6aaed6071c5
